# Generated by Django 3.0.5 on 2020-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0002_auto_20200421_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
