# Generated by Django 3.0.5 on 2020-04-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0004_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='pasantias.Facultad'),
        ),
    ]
