# Generated by Django 3.0.5 on 2020-04-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0005_auto_20200422_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='facultad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
    ]
