# Generated by Django 3.0.5 on 2020-04-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0006_auto_20200422_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='facultad',
        ),
    ]
