# Generated by Django 3.0.5 on 2020-04-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0008_auto_20200422_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='pasantias.Empresa'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='pasantias.Usuario'),
        ),
    ]
