# Generated by Django 3.0.5 on 2020-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0009_auto_20200422_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='facultad',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
