# Generated by Django 3.0.5 on 2020-05-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0012_auto_20200512_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
