# Generated by Django 3.0.5 on 2020-05-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0013_facultad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='facultad',
        ),
    ]
