# Generated by Django 3.0.5 on 2020-05-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasantias', '0014_remove_empresa_facultad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.AddField(
            model_name='empresa',
            name='facultad',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
